# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Anyquery < Formula
  desc "Anyquery is a query engine that allows you to query anything over SQL."
  homepage "https://anyquery.dev"
  version "0.1.0"
  license "AGPL-3.0"

  on_macos do
    on_intel do
      url "https://github.com/julien040/anyquery/releases/download/0.1.0/anyquery_Darwin_x86_64.tar.gz"
      sha256 "25a060a51be058558397f2f1814ad002db852fe165ce98552cb25f02a1f09e89"

      def install
        bin.install "anyquery"
      end
    end
    on_arm do
      url "https://github.com/julien040/anyquery/releases/download/0.1.0/anyquery_Darwin_arm64.tar.gz"
      sha256 "041bfb8cd0f3aa68e0d77dbe59de06837bffe46207e4bde044357c06f16310a8"

      def install
        bin.install "anyquery"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/julien040/anyquery/releases/download/0.1.0/anyquery_Linux_x86_64.tar.gz"
        sha256 "7cfca4953d0514603f7f6d942cc36d847cccf92ade76318fd5b6cebd3fa2d661"

        def install
          bin.install "anyquery"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/julien040/anyquery/releases/download/0.1.0/anyquery_Linux_arm64.tar.gz"
        sha256 "85148edfeec482474c53dd8f8b823ead57f0db99b7a3950e4088a192cc26feea"

        def install
          bin.install "anyquery"
        end
      end
    end
  end
end
