# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Anyquery < Formula
  desc "Anyquery is a query engine that allows you to query anything over SQL."
  homepage "https://anyquery.dev"
  version "0.1.3"
  license "AGPL-3.0"

  on_macos do
    on_intel do
      url "https://github.com/julien040/anyquery/releases/download/0.1.3/anyquery_Darwin_x86_64.tar.gz"
      sha256 "70045b088f714257a7f60faaa47757eef95d57b57a7fc65e987894a42128f3cf"

      def install
        bin.install "anyquery"
      end
    end
    on_arm do
      url "https://github.com/julien040/anyquery/releases/download/0.1.3/anyquery_Darwin_arm64.tar.gz"
      sha256 "4d25f4ee5b51d5d9a70c9dddbccfb7b4242c03f4c696bb6207f814c7fa7eee80"

      def install
        bin.install "anyquery"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/julien040/anyquery/releases/download/0.1.3/anyquery_Linux_x86_64.tar.gz"
        sha256 "088b6a527a22984d4d608b96cca88be4ca9875dc90f54908991d1eb32dab3432"

        def install
          bin.install "anyquery"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/julien040/anyquery/releases/download/0.1.3/anyquery_Linux_arm64.tar.gz"
        sha256 "bb5e0e9b189662dc7c53930d7d241dad77fc8dc3a9ec2b742fa971de05dfd44e"

        def install
          bin.install "anyquery"
        end
      end
    end
  end
end
